### ISSUE TITLE
Support staring not from $GOPATH

### ISSUE THREAD

**Issue by mkevac** [thewhitetulip/Tasks#17]
It would be great if all templates and stuff were in binary and I could start Tasks from any directory with db inside.

**Comment by thewhitetulip** [comment]
Yes, I know that, but the thing is when we ship even the static files inside the binary, it's quite difficult when we scale the application. The best advantage that approach has, is to be able to run Tasks from any folder.

In my machine I have two versions of Tasks, I call one as dev and another as prod, the dev one resides in my `$GOPATH` but the prod one resides in `~/Tasks` and each time while instantiating Tasks, I have to go to `~/Tasks`.

Another point I'd like to note is that Tasks is a webapp, it is of significant importance to have one binary when it comes to a command line application, but for webapps, to the best of my knowledge, it's better to separate static files from the main logic.

We do have one solution to this, we can have env variables to denote the deployment path, this way we can run Tasks from any folder

I'd love to hear your thoughts on this!
