### ISSUE TITLE
Can't build it

### ISSUE THREAD

**Issue by ghost** [thewhitetulip/Tasks#21]
Hi i tried to run the instruction but when I ran go get and tired to build it I got this:

Users/noby > go get github.com/thewhitetulip/Tasks
github.com/thewhitetulip/Tasks/views
Golang/src/github.com/thewhitetulip/Tasks/views/api.go:31: invalid operation: token.Claims["username"](type jwt.Claims does not support indexing)
Golang/src/github.com/thewhitetulip/Tasks/views/api.go:32: invalid operation: token.Claims["exp"](type jwt.Claims does not support indexing)
Golang/src/github.com/thewhitetulip/Tasks/views/api.go:54: invalid operation: token.Claims["username"](type jwt.Claims does not support indexing)

/Users/noby/Golang/src/github.com/thewhitetulip/Tasks > ls
README.md   config.json files       public      screenshots templates   utils
config      db          main.go     schema.sql  sessions    types       views

/Users/noby/Golang/src/github.com/thewhitetulip/Tasks > cat schema.sql | sqlite3 tasks.db
/Users/noby/Golang/src/github.com/thewhitetulip/Tasks > ls

README.md   config.json files       public      screenshots tasks.db    types       views
config      db          main.go     schema.sql  sessions    templates   utils

/Users/noby/Golang/src/github.com/thewhitetulip/Tasks > go build
github.com/thewhitetulip/Tasks/views
views/api.go:31: invalid operation: token.Claims["username"](type jwt.Claims does not support indexing)
views/api.go:32: invalid operation: token.Claims["exp"](type jwt.Claims does not support indexing)
views/api.go:54: invalid operation: token.Claims["username"](type jwt.Claims does not support indexing)

**Comment by thewhitetulip** [comment]
I'll look into it today

**Comment by thewhitetulip** [comment]
@norbertfuhs Can you please check if you can recreate this now? I pushed two commits which were local and not published to Github

**Comment by wolfgangihloff** [comment]
```
# github.com/thewhitetulip/Tasks/views
src/github.com/thewhitetulip/Tasks/views/api.go:31: invalid operation: token.Claims["username"] (type jwt.Claims does not support indexing)
src/github.com/thewhitetulip/Tasks/views/api.go:32: invalid operation: token.Claims["exp"] (type jwt.Claims does not support indexing)
src/github.com/thewhitetulip/Tasks/views/api.go:54: invalid operation: token.Claims["username"] (type jwt.Claims does not support indexing)
ihloff-osx:Tasks ihloff$ go build
# github.com/thewhitetulip/Tasks/views
src/github.com/thewhitetulip/Tasks/views/api.go:31: invalid operation: token.Claims["username"] (type jwt.Claims does not support indexing)
src/github.com/thewhitetulip/Tasks/views/api.go:32: invalid operation: token.Claims["exp"] (type jwt.Claims does not support indexing)
src/github.com/thewhitetulip/Tasks/views/api.go:54: invalid operation: token.Claims["username"] (type jwt.Claims does not support indexing)
```

Is what I get now.

**Comment by ghost** [comment]
Thats the problem in the new version of jwt-go Token.claims is now an interface type  
 [/jwt-go/blob/master/MIGRATION_GUIDE.md](https://github.com/dgrijalva/jwt-go/blob/master/MIGRATION_GUIDE.md)

**Comment by thewhitetulip** [comment]
@norbertfuhs @wolfgangihloff 
As of now, I have pushed an update (https://github.com/thewhitetulip/Tasks/commit/55027eee20f93ae84de6e2b2cb43a5ae13cb573e
) after checking if it works with the latest version, in future I'll implement the latest jwt-go and provide a command line utility along with Tasks.

Thank you!

**Comment by thewhitetulip** [comment]
@norbertfuhs @wolfgangihloff Fixed the error. 

https://github.com/thewhitetulip/Tasks/commit/f94da496ebcfad06ad5d6a0beb0823d4f2679125 Fixes the issue. Thanks for raising it!
