### ISSUE TITLE
api.go EOF 

### ISSUE THREAD

**Issue by ghost** [thewhitetulip/Tasks#22]
noby@Jupiter:~$ go get github.com/thewhitetulip/Tasks
Golang/src/github.com/thewhitetulip/Tasks/main.go:14:2: 
Golang/src/github.com/thewhitetulip/Tasks/views/api.go:639:6: expected 'package', found 'EOF'

**Comment by thewhitetulip** [comment]
@norbertfuhs Thank you! I am in the middle of a re-write of this app an my corresponding book at http://github.com/thewhitetulip/web-dev-golang-anti-textbook/

I'll be updating the API section of Tasks and the book. Do take a look at the book if you have time!
