### ISSUE TITLE
 Tasks/db/tasks.go  runtime error after try to login with new user 

### ISSUE THREAD

**Issue by ghost** [thewhitetulip/Tasks#24]
Hi after i tried to login with an new user i  got an runtime error.

I'm not an SQL expert but it seems there is a column missing. 

Here is the output:

016/08/30 15:08:22 getting tasks for  pending
2016/08/30 15:08:22 no such column: t.hide
2016/08/30 15:08:22 http: panic serving 192.168.1.2:51734: runtime error: invalid memory address or nil pointer dereference
goroutine 50 [running]:

It must be in this file: [ Tasks/db/tasks.go](https://github.com/thewhitetulip/Tasks/blob/master/db/tasks.go)

And these are the columns of the table **task** in **task.db**

![sql-snapshot](https://cloud.githubusercontent.com/assets/17197786/18090922/32194f56-6ec7-11e6-8b7e-22117129949d.png)

What I'm doing wrong and what does the column t.hide exactly do?

**Comment by thewhitetulip** [comment]
`t.hide` is int which says if the particular task will.be hidden from timeline

the idea is that I want to use the Tasks as a todo list manager and as a diary so I wanted tasks to have the ability to hide a partcular task.

a friend of mine got the same error few hours ago :)

I am going to write Go program to deploy code from the repo

**Comment by thewhitetulip** [comment]
solution

`alter table task add hide int;` I  will push a commit in an hour

**Comment by ghost** [comment]
Thanks ! I will try it :+1:  :)

**Comment by thewhitetulip** [comment]
cf1edf72e85d1b140e40d977a5b2f35077fb640a we now have single click deployment with a bash script. :)
