### ISSUE TITLE
Build instructions don't work

### ISSUE THREAD

**Issue by benkasminbullock** [thewhitetulip/Tasks#3]
The build instructions in README.md don't work:

<pre>
How you install?
==================

1. `go get github.com/thewhitetulip/Tasks`
1. change dir to the respective folder and create the db file: `cat schema.sql | sqlite3 tasks.db`
1. run `go build`
1. ./Task
1. open [localhost:8080](http://localhost:8080)
</pre>

`go build` gives an error

main.go:9:2: cannot find package "github.com/thewhitetulip/Tasks/views" in any of:
    /usr/local/go/src/github.com/thewhitetulip/Tasks/views (from $GOROOT)
    /home/ben/projects/golib/src/github.com/thewhitetulip/Tasks/views (from $GOPATH)

I found that this worked:

   $ go get github.com/thewhitetulip/Tasks/views
   $ go build

**Comment by thewhitetulip** [comment]
But shouldn't Go get the dependencies resolved by itself? Also should I add the `go get github.com/thewhitetulip/Tasks/views` line to build instructions?

Also I had tried the build instructions on Linux, it had worked.

**Comment by thewhitetulip** [comment]
@benkasminbullock Do you have any suggestions? Also I updated three chapters in the book just now :-)

**Comment by thewhitetulip** [comment]
@benkasminbullock  Do they work now? I have updated a _lot_ of things in the past few days like task list and stuff

**Comment by tlongren** [comment]
@thewhitetulip they work just fine for me on Xubuntu 15.10.

**Comment by thewhitetulip** [comment]
@tlongren I guess @benkasminbullock might have had an older source code tree and that's why the issue was created. @benkasminbullock I am closing the issue, please let me know if you are facing problems
