### ISSUE TITLE
"Restore" removes from "Deleted" but doesn't restore

### ISSUE THREAD

**Issue by benkasminbullock** [thewhitetulip/Tasks#5]
As far as I can see the "Restore" button removes the thing from "Deleted" but not from "Completed" but it doesn't restore it to "Pending".

**Comment by thewhitetulip** [comment]
The thing is what I meant by restore was that the task should be removed from the recycle bin, I have to work on restoring it to pending by giving an option "mark as incomplete" in the completed view.

**Comment by thewhitetulip** [comment]
cf9cb0eea56606202678a70a17485c5f191615d9 
fixes the issue
