### ISSUE TITLE
syntax errors in views.go

### ISSUE THREAD

**Issue by blazk** [thewhitetulip/Tasks#7]
The code does not compile - contains conflict markers:

<<<<<<< HEAD

etc

**Comment by thewhitetulip** [comment]
https://github.com/thewhitetulip/Tasks/commit/25a6ffc8b2310f8b4ad645dffa53ab3da78194f9
Solves the issue. Actually I had fixed them on my machine but forgotten to push them upstream.
This commit also adds github flavoured markdown! like lists, github style code formatting and more!
