### ISSUE TITLE
"no such file or directory" when uploading a file

### ISSUE THREAD

**Issue by tlongren** [thewhitetulip/Tasks#8]
```
2016/01/30 05:29:32 running server on  :8081
2016/01/30 05:31:06 open ./files/d63f1c1d67c9f3c529e345005937bf19: no such file or directory
2016/01/30 05:31:39 http: no such file
2016/01/30 05:31:40 added task to db
2016/01/30 05:34:16 open ./files/b143847434d2c757593b27472dc69f55: no such file or directory
```

Guessing it has something to due with no _files_ directory. :)

**Comment by thewhitetulip** [comment]
This is embarrassing :smile: 
Thank you for pointing it out!
While manually testing the app I had uploaded a lot of files, so I thought they might get into the tree, I never realized that people won't have the `files` folder  

https://github.com/thewhitetulip/Tasks/commit/65506a7723d718976f8f4cad752bcaedcb408bf9 fixes it
