### ISSUE TITLE
Multiple list support

### ISSUE THREAD

**Issue by tnjd** [thewhitetulip/Tasks#9]
like in Wunderlist

**Comment by thewhitetulip** [comment]
I am sorry I have never used Wunderlist, can you please elaborate?
Do you mean add item to multiple lists? or lists within list? or the subtask feature shown in their home page?

**Comment by thewhitetulip** [comment]
I thought about it, do you mean categories?

**Comment by tnjd** [comment]
I mean multiple lists that have different sets of tasks, for example a user might have a shopping list, a list of things to do for work etc

**Comment by thewhitetulip** [comment]
Well that means categories right? which'll reside on the collapsible drawer? 
categories = tags for tasks I guess which you are calling lists. Am I right?

**Comment by thewhitetulip** [comment]
@expectocode https://github.com/thewhitetulip/Tasks/commit/5bdbe6f7b23c05a42878c0bc30c95565b182eefb Fixes this issue :-)
Thank you very much for your feature request! Had you never raised this issue, I would have been lazy to add this feature :smile:
